Add feature to list author tricks
OFFLINE-GmbH/octobertricks.com pull request #17
Opened 2020-02-21 06:00 UTC by LarBearrr

The initial feature has been implemented by creating a new page and using the `TrickList` component. This component was updated to check for a username property, which is used to set the component's user based on the route parameter `:username`. If no user is found, the component will return the `404` page 

See #14 

**TODO**

- [ ] Fix issue with 404 page not showing search box. If you attempt to visit the trick list for an author that cannot be found, the search box is not displayed. Other invalid routes do show the search box on the 404 page.
- [ ] Add links to author trick list from home page
- [ ] Add link to author trick list from trick detail page

2020-02-21 07:26 UTC, tobias-kuendig requested changes
Looking great, thanks @LarBearrr!

2020-02-21 07:26 UTC, tobias-kuendig commented on themes/october-tricks/pages/homepage.htm
> +                by <a class="author" href="/authors/{{trick.author.username}}/tricks">{{ trick.author.username }}</a>
```suggestion
                by <a class="author" href="{{ 'author-tricks' | page({username: trick.author.username}) }}">{{ trick.author.username }}</a>
```

2020-02-21 07:26 UTC, tobias-kuendig commented on themes/october-tricks/partials/medium-trick.htm
> +                    by <a class="author" href="/authors/{{trick.author.username}}/tricks">{{ trick.author.username }}</a>
```suggestion
                    by <a class="author" href="{{ 'author-tricks' | page({username: trick.author.username}) }}">{{ trick.author.username }}</a>
```

2020-02-21 07:26 UTC, tobias-kuendig commented on themes/october-tricks/partials/small-trick.htm
> +        by <a class="author" href="/authors/{{trick.author.username}}/tricks">{{ trick.author.username }}</a>
```suggestion
        by <a class="author" href="{{ 'author-tricks' | page({username: trick.author.username}) }}">{{ trick.author.username }}</a>
```

2020-02-21 07:26 UTC, tobias-kuendig commented on themes/october-tricks/partials/trickDetail/trick.htm
> +            by <a class="author" href="/authors/{{trick.author.username}}/tricks">{{ trick.author.username }}</a>, last modified on {{ trick.updated_at.format('F jS, Y') }}
```suggestion
            by <a class="author" href="{{ 'author-tricks' | page({username: trick.author.username}) }}">{{ trick.author.username }}</a>, last modified on {{ trick.updated_at.format('F jS, Y') }}
```

2020-02-21 07:26 UTC, tobias-kuendig commented on themes/october-tricks/resources/styl/base/base.styl
> +.author:hover
```suggestion
    &:hover
```

2020-02-23 03:11 UTC, LarBearrr commented
@tobias-kuendig Do you want to do anything about the 404 page not showing the search box?

2020-03-06 06:21 UTC, tobias-kuendig commented
> Do you want to do anything about the 404 page not showing the search box?

Would be nice, but it's definitely low on the list of priorities right now ;) 

Thank you for this contribution!

2020-03-06 06:22 UTC, merged

2020-03-07 02:33 UTC, LarBearrr commented
Yeah, I just finished my last class at university so I’ll have more free time now.